# Generated by Django 4.1.7 on 2023-03-24 11:05

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=app.models.getfilename)),
                ('description', models.TextField(max_length=500)),
                ('status', models.BooleanField(default=False, help_text='0-default,1-hidden')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('vendor', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.IntegerField()),
                ('old_price', models.FloatField()),
                ('new_price', models.FloatField()),
                ('pro_image', models.ImageField(blank=True, null=True, upload_to=app.models.getfilename)),
                ('description', models.TextField(max_length=500)),
                ('status', models.BooleanField(default=False, help_text='0-default,1-hidden')),
                ('trending', models.BooleanField(default=False, help_text='0-default,1-trending')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('catagories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.catagories')),
            ],
        ),
    ]
