# Generated by Django 4.1.7 on 2023-04-03 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_sample'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sample',
        ),
    ]
